"""fixed the spelling and updated the db

Revision ID: 39f91dda8654
Revises: f9b7c7d9310f
Create Date: 2026-08-25 21:07:06.951872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f91dda8654'
down_revision: Union[str, Sequence[str], None] = 'f9b7c7d9310f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount_paid', sa.Integer(), nullable=False))
    op.drop_column('payments', 'amount_payed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount_payed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'amount_paid')
    # ### end Alembic commands ###
