"""Updated the Database added the enums and also seperated the payment and extended room booking from main table

Revision ID: 47a9a3edec4d
Revises: 
Create Date: 2026-08-24 13:22:40.875164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a9a3edec4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', 'SUITE', name='roomtype'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('room_status', sa.Enum('AVAILABLE', 'OCCUPIED', 'CLEANING', 'MAINTENANCE', name='roomstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checkout_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_status', sa.Enum('RESERVED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extended_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_book_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_book_id'], ['room_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_book_id', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.Enum('PAID', 'UNPAID', 'EXTENDED', name='paymentstatus'), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('extended_room_amount', sa.Integer(), nullable=False),
    sa.Column('grand_total', sa.Integer(), nullable=False),
    sa.Column('amount_payed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_book_id'], ['room_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('extended_rooms')
    op.drop_table('room_bookings')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
