"""Added create_at column and also fixes the naming of other columns

Revision ID: 7e7ad8aa203c
Revises: 47a9a3edec4d
Create Date: 2026-08-24 13:50:36.419098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e7ad8aa203c'
down_revision: Union[str, Sequence[str], None] = '47a9a3edec4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_bookings', sa.Column('check_in_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('room_bookings', sa.Column('check_out_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('room_bookings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('room_bookings', 'booked_at')
    op.drop_column('room_bookings', 'checkout_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_bookings', sa.Column('checkout_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('room_bookings', sa.Column('booked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('room_bookings', 'created_at')
    op.drop_column('room_bookings', 'check_out_date')
    op.drop_column('room_bookings', 'check_in_date')
    # ### end Alembic commands ###
