"""Updated the table , fixed enums

Revision ID: f9b7c7d9310f
Revises: 7e7ad8aa203c
Create Date: 2026-08-25 16:23:22.863111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b7c7d9310f'
down_revision: Union[str, Sequence[str], None] = '7e7ad8aa203c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
